version: "3.8"
services:
  db:
    image: postgres:16
    container_name: kook_orders_db
    environment:
      POSTGRES_USER: kook
      POSTGRES_PASSWORD: kookpass
      POSTGRES_DB: kook_orders
      TZ: "UTC"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
